# ECE/CS 434 | MP6: Dynamic Time Warping
<br />
<nav>
    <span class="alert alert-block alert-warning">Due on Thursday May 1st 11:59PM on Gradescope</span>
</nav><br> 


----
## Objective
In this MP, you will:
- Implement the Dynamic Time Warping Algorithm
- Use the DTW algorithm to identify missing windows in time series data

----
## Imports

In [5]:
import numpy as np
import random
import scipy



# This function is used to format test results. You don't need to touch it.
def display_table(data):
    from IPython.display import HTML, display

    html = "<table>"
    for row in data:
        html += "<tr>"
        for field in row:
            html += "<td><h4>{}</h4><td>".format(field)
        html += "</tr>"
    html += "</table>"
    display(HTML(html))

----
## Problem Setting
Many off-the-shelf smart watches today are capable of taking the user's electrocardiogram (also called an ECG or EKG), a test that records the timing and strength of the electrical signals that make the heart beat. However, wearing the watch too loose, having sweat or dirt between the watch and wrist can all result in poor readings. In this MP, we will simulate this scenario. You will be given a ground truth reading $X$, and a watch reading $Y$. The watch reading will have 1 missing time window and added noise compared to the ground truth reading. In other words, $Y = X\setminus W + N$, where $W$ is the missing time window and $N$ is random noise. Your task is to identify the start of the missing time window.

For example, let $X = [1, 2, 3, 4, 5]$ and $Y = [0.9, 2.1, 5.2]$. We can see that the values $3$ and $4$ in $X$ are missing from $Y$. Your program should then return $2$, which is the index of the first missing value in $X$, aka the index of $3$ in $X$

Note that we are only simulating an ECG missing data scenario. The data used is not actually ECG data. However, this should not make a difference in your implementation.

<div class="alert alert-block alert-info"><b>Hint 1:</b> The DTW algorithm essentially constructs a cost matrix, $C$, between the two signals, based on the distance between points in the two signals. For every cell in this matrix, its value can be calculated as such: $C(c_j, r_j) = distance(c_j,r_j) + min\{C(c_{j-1}, r_{j-1}), C(c_{j-1, r_{j}}), C(c_{j}, r_{j-1})\}$. Refer to the lecture notes for more details.</div>

<div class="alert alert-block alert-info"><b>Hint 2:</b> The missing time window can be identified by examining the cost matrix: 1 time point in $Y$ will match to multiple time points in $X$. You can approach this by starting at (0, 0) of the cost matrix and traveling towards (len(X), len(Y)). At every step, make a decision to go right, down or diagonal by choosing the cell with minimal cost. If for multiple steps in a row, the decision is to go down, then you might have encountered the missing time window since 1 point in $Y$ is being matched to multiple points in $X$</div>

----
## Your Implementation
Implement your algorithm in the function `find_missing_window(X, Y, N)`. Do **NOT** change its function signature. You are, however, free to define and use helper functions. You are **NOT** allowed to use existing Python DTW packages.

In [47]:
def find_missing_window(X, Y, N):
    """Identifies where data is missing.
    Args:
      X: The ground truth signal
      Y: Signal with 1 time window missing from X and added noise
      N: Approximate length of the missing time window
    Returns: Candidate indices of the missing time window in X. See section above for an example.
    You may return up to 3 candidate results. You will receive full points as long as 1 falls within the grading criteria.
    For example, if you think the missing time window starts at index 3 but indices 8 and 40 are also possible, 
    then return [3, 8, 40].
    """
    x_len = len(X)
    y_len = len(Y)
    cost_matrix = np.zeros((x_len,y_len))
    
    
    # initialize top row and left column of cost_matrix
    for a in range(1, y_len):
      cost_matrix[0,a] = np.abs(X[0] - Y[a]) + cost_matrix[0,a-1]
    for b in range(1, x_len):
      cost_matrix[b,0] = np.abs(X[b] - Y[0]) + cost_matrix[b-1, 0]
    
    for row in range(1,x_len):
      for col in range(1, y_len):
        cost_matrix[row,col] = np.abs(X[row] - Y[col]) + np.min([cost_matrix[row-1,col], cost_matrix[row,col-1], cost_matrix[row-1,col-1]])
    print(cost_matrix)
    one_hot_x_down = np.zeros(x_len, int)
    
    current_point = np.array([0,0], int)
    x,y = current_point
    for a in range(x_len):

      # values
      down = np.inf if current_point[0] + 1 == x_len else cost_matrix[current_point[0] + 1, current_point[1]]
      right = np.inf if current_point[1] + 1 == y_len else cost_matrix[current_point[0], current_point[1] + 1 ]
      diag = np.inf if current_point[0] + 1 == x_len or current_point[1] + 1 == y_len else cost_matrix[current_point[0] + 1, current_point[1] + 1]
      
      # What to advance x, y?
      x_down_diag_right = np.array([1,1,0]) # What to advance x, y?
      y_down_diag_right = np.array([0,1,1])
      
      #  values
      down_diag_right = np.array([down,diag,right]) # order of these elements is down, diag, right
      min_direction =np.argmin(down_diag_right) # 0 means down, 1 means diagonal, 2 means right
      
      if min_direction == 0: # we moved down, which means there was missing time stamp
        one_hot_x_down[a] = 1
      else:
        one_hot_x_down[a] = 0
      current_point[0] += x_down_diag_right[min_direction]
      current_point[1] += y_down_diag_right[min_direction]
    
    print(one_hot_x_down)
    
    # Perform correlation based on one_hots
    
    hot_indices = []
    # hot_sums = np.zeros(x_len) # sum the hot_sums
    for a in range(x_len):
      if one_hot_x_down[a] == 1:
        is_possible_index = True
        for i in range(N-5): # Check if we have N-3 1s in a row
          if a + i >= x_len:
            break
          if one_hot_x_down[a + i] == 0:
            is_possible_index = False
            break
        if is_possible_index:
          hot_indices.append(a)
      if len(hot_indices) == 3:
        break
            
      
    print(hot_indices)
    
    print("\n\n")
    
    
    
    return [hot_indices[0], hot_indices[1], hot_indices[2]]

---
## Running and Testing
Use the cell below to run and test your code, and to get an estimate of your grade.

In [48]:
def calculate_score(groundtruth, candidates, threshold):
    for candidate in candidates:
        if(groundtruth - threshold < candidate < groundtruth + threshold):
            return 1
    return 0
import matplotlib.pyplot as plt    
if __name__ == '__main__':
    output = [['Test', 'Correct Index', 'Calculated Indices', 'Grade']]
    windows = [3, 5, 56, 32] # 20
    N = [2, 2, 4, 5]
    for i in range(4):
        X = np.loadtxt(open('{}_X.csv'.format(i), "rb"), delimiter=",", skiprows=1)
        Y = np.loadtxt(open('{}_Y.csv'.format(i), "rb"), delimiter=",", skiprows=1)
        student_answer = find_missing_window(X, Y, N[i])
        score = calculate_score(windows[i], student_answer, max(4, N[i] * 0.5))
        output.append([i, windows[i], student_answer, "{:0.0f} / 10".format(score * 10)])
    output.append(['<i>👻 Hidden test 0 👻</i>','<i>???</i>', '<i>???</i>', '<i>???</i> / 10'])
    output.append(['<i>👻 Hidden test 1 👻</i>','<i>???</i>', '<i>???</i>', '<i>???</i> / 10'])
    output.append(['<i>👻 Hidden test 2 👻</i>','<i>???</i>', '<i>???</i>', '<i>???</i> / 10'])
    output.append(['<i>👻 Hidden test 3 👻</i>','<i>???</i>', '<i>???</i>', '<i>???</i> / 10'])
    display_table(output)

[[0.        0.0012818 0.0039063]
 [0.0012818 0.        0.0013427]
 [0.0020906 0.000473  0.0018157]
 [0.0031588 0.0006866 0.0020293]
 [0.0057833 0.0020293 0.0006866]]
[0 1 1 0 1]
[1, 2, 4]



[[0.00000000e+00 1.23750000e-02 2.66728000e-02 ... 3.59310278e+00
  3.59468978e+00 3.59710078e+00]
 [1.23750000e-02 0.00000000e+00 1.92280000e-03 ... 2.86411878e+00
  2.87808078e+00 2.88804478e+00]
 [2.66728000e-02 1.92280000e-03 0.00000000e+00 ... 2.76605598e+00
  2.78194078e+00 2.79382758e+00]
 ...
 [3.64757728e+00 2.89384328e+00 2.79193488e+00 ... 1.68917000e-02
  2.02637000e-02 2.76337000e-02]
 [3.64916428e+00 2.90780528e+00 2.80781968e+00 ... 2.02637000e-02
  1.68917000e-02 2.08897000e-02]
 [3.65157528e+00 2.91776928e+00 2.81970648e+00 ... 2.76337000e-02
  2.08897000e-02 1.68917000e-02]]
[0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

---
## Rubric
You will be graded on the four datasets provided to you (10 points each) and four additional datasets. We will use the same code from the **Running and Testing** section above to grade all 8 traces of data. As long as 1 of 3 candidate outputs are within the grading threshold($max[4, window\_size \times 0.5]$), you will receive 10 points. No partial credit is rewarded since we are essentially allowing 3 guesses.

----
## Submission Guidelines
This Jupyter notebook (`MP6.ipynb`) is the only file you need to submit on Gradescope. Since this is the last MP, you can expect the grade you see on Gradescope to be the final grade of this MP. Regrade requests are not accepted.

**Make sure any code you added to this notebook, except for import statements, is either in a function or guarded by `__main__`(which won't be run by the autograder). Gradescope will give you immediate feedback using the provided test cases. It is your responsibility to check the output before the deadline to ensure your submission runs with the autograder.**